<<<<<<< HEAD
export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

=======
export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

>>>>>>> f448bad4f036de52f959871a25d19a6ada588716
