export const ADD_INGRIDIENT = "ADD_INGRIDIENT";
export const REMOVE_INGRIDIENT = "REMOVE_INGRIDIENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

export const RESETSET_INGRIDIENTS = "RESETSET_INGRIDIENTS";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";
